<?php
define('DIR_ROOT', __DIR__.DIRECTORY_SEPARATOR);
define('VIEWS', DIR_ROOT.'views'.DIRECTORY_SEPARATOR);
define('MODELS', DIR_ROOT.'models'.DIRECTORY_SEPARATOR);
define('USE_CASES', DIR_ROOT.'use-cases'.DIRECTORY_SEPARATOR);